name: Reviz Tests

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  reviz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Setup Turbo cache
        uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: Build
        run: yarn turbo build

      - name: Build Storybook
        working-directory: example
        run: yarn build-storybook
      
      - name: Run reviz
        working-directory: example
        run: yarn reviz

      - name: Upload Artifact
        if: success() || failure()
        uses: actions/upload-artifact@v2
        with:
          name: reviz-output
          path: ./example/.reviz
