name: Reviz Tests

on: 
  push:
  pull_request: [main]

jobs:
  reviz:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          cache: 'yarn'

      - name: Install dependencies
        run: yarn
      
      - name: Run reviz
        working-directory: example
        run: yarn reviz
